<a href="https://colab.research.google.com/github/elainedias16/TCC/blob/main/Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classificador

## Motivação

A classificação é uma subárea do aprendizado de máquina, inserida no campo do aprendizado supervisionado. O objetivo da classificação é treinar modelos para categorizar dados em diferentes classes predefinidas, permitindo que o modelo aprenda a associar entradas a suas respectivas categorias com base em exemplos rotulados.

No Processamento de Linguagem Natural (NLP), a classificação desempenha um papel crucial. Ao lidar com grandes volumes de texto, a classificação permite organizar e categorizar informações de forma automática, facilitando a extração de insights para tomada de decisões. São exemplos de classificação em NLP, os problemas de classificação de emails como *spam * ou *não spam*, detecção do tema de um texto, detecçao do idioma do texto, dentre outros exemplos. Portanto, o estudo da classificação em NLP é fundamental para otimizar o tratamento e a análise de dados




## Resultados Esperados

Neste laboratório, espera-se que o aluno compreenda a importância da classificação na área de NLP e aprenda a aplicá-la em um conjunto de dados, comparando diferentes modelos. Essa comparação dos modelos será feita
por meio das métricas tradicionais da classificação, como acurácia, precision, recall, entre outras. Dessa forma, o aluno também poderá reforçar o aprendizado desses conceitos.

## Fundamentação teórica

A classificação é uma tarefa do aprendizado supervisionado em que, dado um conjunto de dados rotulados, é criado um modelo que aprende a partir desses dados e se torna capaz de realizar predições para novos exemplos.  A classificação pode ser utilizada nas áreas de saúde, marketings, finanças, tecnologia, entre outras, sendo bastante comum em NLP, em problemas de análise de sentimento, reconhecimento de intenção, classificação de temas, entre outros.
Devido a grande importância da classificação, foram criados diversos algortimos ao longo do tempo para categorizar diferentes dados, tais como : k-Nearest Neighbors (k-NN) , Árvores de Decisão, Random Forest, Naive Bayes, entre outros.

Neste laboratório, será feita a classificação de uma base de dados de notícias. Dessa forma, serão realizadas as seguintes etapas:

### Divisão dos dados em treino e teste

O conjunto de dados que será dividido em treino e teste. Uma vez que serão utilizados classificadores da biblioteca *sckit-learn* e não será feito ajuste de parâmetros, optou-se por não criar um conjunto de validação. Assim, foi definido uma porcentagem de 20% para os dados de teste e 80% para os dados de treino. Vale ressaltar que essa porcentagem foi aplicada a cada classe do conjunto de notícias, garantindo que todos os rótulos estivessem presentes tanto no conjunto de treino quanto no conjunto de teste.


### Criação do dicionário de palavras únicas do treino

Essa etape consiste um criar um índice de palavras do conjunto de treino.

### Criação de embeddings

Os modelos de classificação processsam apenas números. Dessa forma, é preciso tranformar cada arquivo em um vetor númerico, a fim de serem processados pelos algoritmos. Para tal, seram utitilizados três abordagens:

#### Vetor Binário

Nessa abordagem, cada documento é transformado em um vetor binário, onde 1 indica a presença de uma palavra e 0 indica sua ausência. A análise de presença ou ausência de palavras é realizada com base no dicionário de palavras únicas criado a partir do conjunto de treino.  Assim, o vetor binário terá o mesmo tamanho do voculário, sendo que para cada palavra *i* do conjunto de treino, será inserido 0 ou 1 no vetor binário, indicando se essa palavra está presente no documento analisado ou não. Note que os vetores gerados serão esparsos.


#### Vetor de Frequência

Nessa abordagem, cada posição do vetor de frequência representa a frequência da palavra *i* do conjunto de treino em um documento *x*. Asssim, os vetores gerados terão o mesmo tamanho do vocabulário, isto é, o tamanho do dicionário de palavras únicas do treino.

#### Term Frequency – Inverse Document Frequency (TF-IDF)

O TF-IDF é uma técnica que cálcula a frequência de um termo, considerando o inverso de sua frequência dos documentos.  No método de calcular a frequência, considera-se que quanto mais um termo aparece em documento, maior a sua relevância. Apesar disso, existem termos que possuem alta frequência em todos os documentos, mas não acrescentam informção semântica. Dessa forma, o TF-IDF busca equilibrar esses conceitos, realizando a divisão entre as métricas.

A fórmula do TF-IDF é dada por:

$$
\text{TF-IDF}(t, d, D) = \text{TF}(t, d) \times \text{IDF}(t, D)
$$

Onde:

- \(\text{TF}(t, d)\) é a frequência do termo \( t \) no documento \( d \):

$$
\text{TF}(t, d) = \frac{\text{Número de ocorrências de } t \text{ em } d}{\text{Número total de palavras em } d}
$$

- \(\text{IDF}(t, D)\) é a frequência inversa do documento para o termo \( t \):

$$
\text{IDF}(t, D) = \log \frac{\text{Número total de documentos em } D}{1 + \text{Número de documentos contendo } t}
$$





### Treinamento dos classificadores


### Análise de resultados

## Código

### Leitura do Dataset

Download do dataset pré processado.

In [1]:
!wget https://raw.githubusercontent.com/elainedias16/TCC/main/pre_processed_dataset.csv

--2024-08-31 21:03:32--  https://raw.githubusercontent.com/elainedias16/TCC/main/pre_processed_dataset.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 84507 (83K) [text/plain]
Saving to: ‘pre_processed_dataset.csv’

pre_processed_datas 100%[===================>]  82.53K  --.-KB/s    in 0.02s   

2024-08-31 21:03:32 (5.14 MB/s) - ‘pre_processed_dataset.csv’ saved [84507/84507]



In [2]:
import pandas as pd

with open('pre_processed_dataset.csv', 'r') as file:
    lines = file.readlines()


def create_dataframe(path):
    columns=['genre', 'filename', 'title', 'content']
    df =  pd.read_table(
    path,
    header=None,
    names=columns,
    sep= ',',
    engine= 'python'
    )
    return df


df = create_dataframe('pre_processed_dataset.csv')

In [3]:
df = df.drop(0, axis = 0)
df = df.reset_index(drop=True)
df

genre  filename                                  title  \
0        business   288.txt        UK economy facing 'major risks'   
1        business   184.txt       US bank 'loses' customer details   
2        business   471.txt       China suspends 26 power projects   
3        business    35.txt      US gives foreign firms extra time   
4        business   377.txt       Ukraine strikes Turkmen gas deal   
5        business   150.txt      Bank voted 8-1 for no rate change   
6        business   315.txt      Euronext 'poised to make LSE bid'   
7        business   455.txt       Gazprom 'in $36m back-tax claim'   
8        business   206.txt       EMI shares hit by profit warning   
9        business   388.txt     Egypt to sell off state-owned bank   
10       business   316.txt      Christmas shoppers flock to tills   
11  entertainment   512.txt       Musical treatment for Capra film   
12  entertainment   718.txt      US show sued for rat-eating stunt   
13  entertainment   658.txt       Spector facing more legal action   
14  entertainment   637.txt      Top gig award for Scissor Sisters   
15  entertainment   867.txt       Film star Fox behind theatre bid   
16  entertainment   634.txt      Snow Patrol feted at Irish awards   
17  entertainment   861.txt        Vera Drake's Bafta triumph hope   
18  entertainment   559.txt        Willis sues over movie 'injury'   
19  entertainment   540.txt         Dirty Den's demise seen by 14m   
20  entertainment   570.txt         Director Nair's Vanity project   
21  entertainment   534.txt       New Harry Potter tops book chart   
22       politics  1117.txt       Voters 'reject EU by two to one'   
23       politics  1164.txt        Teens 'know little' of politics   
24       politics  1110.txt       New rules tackle 'sham weddings'   
25       politics  1123.txt       Labour pig poster 'anti-Semitic'   
26       politics   927.txt            Hunt demo at Labour meeting   
27       politics  1224.txt      Tory expert denies defeat warning   
28       politics  1215.txt      Hague's six-figure earnings shown   
29       politics  1296.txt       Blair prepares to name poll date   
30       politics   914.txt       Drink remark 'acts as diversion'   
31       politics  1310.txt        Labour MP praises Tory campaign   
32       politics  1199.txt        UKIP outspent Labour on EU poll   
33       politics  1273.txt       Blair defends terror law changes   
34       politics   973.txt        Asylum children to face returns   
35       politics   954.txt       'Debate needed' on donations cap   
36       politics   902.txt        Fox attacks Blair's Tory 'lies'   
37       politics   943.txt       Anglers 'could face prosecution'   
38          sport  1530.txt       Mourinho plots impressive course   
39          sport  1662.txt      Dal Maso in to replace Bergamasco   
40          sport  1675.txt        Calder fears for Scottish rugby   
41          sport  1747.txt                Mirza shocks Kuznetsova   
42          sport  1545.txt             Redknapp poised for Saints   
43          sport  1335.txt        Greek pair attend drugs hearing   
44          sport  1736.txt            Roddick into San Jose final   
45          sport  1665.txt       Scots suffer another injury blow   
46          sport  1590.txt       Robben and Cole earn Chelsea win   
47          sport  1486.txt      Cudicini misses Carling Cup final   
48          sport  1490.txt       Cole refuses to blame van Persie   
49           tech  2033.txt      Toxic web links help virus spread   
50           tech  2189.txt      Rolling out next generation's net   
51           tech  1910.txt        Net regulation 'still possible'   
52           tech  2116.txt        File-swappers ready new network   
53           tech  1824.txt      Ink helps drive democracy in Asia   
54           tech  2181.txt  What price for 'trusted PC security'?   
55           tech  2051.txt       More power to the people says HP   
56           tech  205

### Criação do dataframe para treino e para teste

In [4]:
from sklearn.model_selection import train_test_split

def create_test_training_split(df, percent):
    X_train_list = []
    X_test_list = []
    y_train_list = []
    y_test_list = []
    grouped = df.groupby('genre')

    for genre, group_df in grouped:

          X = group_df.drop('genre', axis='columns')
          y = group_df['genre']
          X_train, X_test, y_train, y_test = train_test_split(  X, y, test_size=percent, random_state=42)

          X_train_list.append(X_train)
          X_test_list.append(X_test)
          y_train_list.append(y_train)
          y_test_list.append(y_test)


    X_train = pd.concat(X_train_list).reset_index(drop=True)
    X_test = pd.concat(X_test_list).reset_index(drop=True)
    y_train = pd.concat(y_train_list).reset_index(drop=True)
    y_test = pd.concat(y_test_list).reset_index(drop=True)
    return X_train, y_train, X_test, y_test






percent_test = 0.2
X_df_train, y_train, X_df_test, y_test = create_test_training_split(df, percent_test)

### Criação do dicionário das palavras do treino

In [5]:
# 3404
def create_unique_words(content):
  words = content.split()

  # dict_words é um dicionário que mapeia uma palavra em um índice
  # agua -> 0
  # casa -> 1
  # bola -> 2
  # ...
  dict_words = {}

  for word in words:
    if word not in dict_words:
      dict_words[word] = len(dict_words)

  return dict_words


content_train = X_df_train['content'].str.cat(sep=' ')
unique_words_set_train = create_unique_words(content_train)
len_unique_words = len(unique_words_set_train)
print(unique_words_set_train)
print(f"len unique_words: {len_unique_words}")

{'shop': 0, 'uk': 1, 'report': 2, 'strong': 3, 'sale': 4, 'last': 5, 'saturday': 6, 'christma': 7, 'claim': 8, 'record': 9, 'break': 10, 'number': 11, 'festiv': 12, 'shopper': 13, 'spokesman': 14, 'manchest': 15, 'trafford': 16, 'centr': 17, 'say': 18, 'big': 19, 'date': 20, '5': 21, 'regent': 22, 'street': 23, 'associ': 24, 'central': 25, 'london': 26, 'also': 27, 'expect': 28, 'good': 29, 'ever': 30, 'pictur': 31, 'come': 32, 'despit': 33, 'disappoint': 34, 'coupl': 35, 'week': 36, 'spokeswoman': 37, '8': 38, '500': 39, 'thousand': 40, 'vehicl': 41, 'arriv': 42, '1130': 43, 'gmt': 44, 'predict': 45, 'next': 46, 'continu': 47, 'trend': 48, 'add': 49, 'similar': 50, 'stori': 51, 'bluewat': 52, 'kent': 53, 'alan': 54, 'jone': 55, '150': 56, '000': 57, 'visit': 58, 'end': 59, '100': 60, 'sunday': 61, 'far': 62, '2': 63, 'time': 64, 'year': 65, 'busi': 66, 'realli': 67, 'peopl': 68, 'right': 69, 'period': 70, 'spend': 71, 'excess': 72, '200': 73, 'afternoon': 74, 'st': 75, 'david': 76, 'c

### Transformando cada notícia em um vetor

#### Vetor one-hot

In [6]:
import numpy as np

def create_binary_array_doc_aux(content, unique_words):
    tokens = content.split()
    binary_array = np.zeros((len(unique_words), ))
    for word in tokens:
        if word in unique_words:  # O(1)
            idx =  unique_words[word]
            binary_array[idx] = 1

    return binary_array


def create_binary_array_docs(df, unique_words):
    binary_words = []
    for index, row in df.iterrows():
        content = row['content']
        binary_array = create_binary_array_doc_aux(content, unique_words)
        binary_words.append(binary_array)

    return binary_words



#Each line represents a docs and its columns represents if there is the respective unique_word in the docs
binary_words_docs = create_binary_array_docs(X_df_train, unique_words_set_train)

print(binary_words_docs)
print(f"len of binary_words_docs: {len(binary_words_docs)}") # Must be igual to the number of docs

[array([1., 1., 1., ..., 0., 0., 0.]), array([0., 1., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 1., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 1., ..., 0., 0., 0.]), array([0., 1., 1., ..., 0., 0., 0.]), array([0., 1., 1., ..., 0., 0., 0.]), array([0., 1., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 1., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 1., ..., 0., 0., 0.]), array([0., 1., 0., ..., 0., 0., 0.]), array([0., 0., 1., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 1., 1., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 0., 0., ..., 0., 0., 0.]), array([0., 1., 0., ..., 0., 0., 0.]), array([0., 1., 0., ..., 0., 0., 0.]), array([0., 

### Frequency of word in docs

In [7]:
def create_word_frequency_aux(content, unique_words):
    tokens = content.split()

    # cria um array de zeros do tamanho do dicionario de palavras diferentes
    tamanho = (len(unique_words), ) # tupla com um elemento
    word_frequency = np.zeros(tamanho)

    for word in tokens: # para cada palavra no texto
        if word in unique_words:  # se a palavra existe no dicionario de palavras unicas
            idx =  unique_words[word] # recupera o indice da palavra
            word_frequency[idx] += 1 # incrementa a frequencia (vimos a palavra mais uma vez)

    return word_frequency


def create_word_frequency(df, unique_words):
  word_frequency = []
  for index, row in df.iterrows():
      content = row['content']
      word_frequency.append(create_word_frequency_aux(content, unique_words))

  return word_frequency

In [8]:
word_docs_frequency = create_word_frequency(X_df_train, unique_words_set_train)

In [9]:
word_docs_frequency

[array([7., 1., 4., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 1., 3., ..., 0., 0., 0.]),
 array([0., 1., 1., ..., 0., 0., 0.]),
 array([0., 2., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 5., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 0., 0.]),
 array([0., 0., 1., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 7., 3., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 0., 0., ..., 0., 0., 0.]),
 array([0., 1., 0., ..., 0., 0., 0.]),
 array([0., 4., 0., ..., 

#### TF-IDF

In [10]:
def calcule_tfidf(frequency_matrix):
  total_docs = len(frequency_matrix)
  # first_column = [row[0] for row in frequency_matrix]
  # print(first_column)
  document_frequency = np.count_nonzero(frequency_matrix, axis=0)
  idf = np.log(total_docs / (1 + document_frequency))
  tfidf = frequency_matrix * idf
  return tfidf


tfidf = calcule_tfidf(word_docs_frequency)
print(tfidf)
print(len(tfidf))
print(len(tfidf[1]))

[[21.63729717  1.29928298  5.54517744 ...  0.          0.
   0.        ]
 [ 0.          1.29928298  0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 ...
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  3.09104245  3.09104245
   3.09104245]]
44
2885


### Treinando os classificadores

In [11]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_test = label_encoder.fit_transform(y_test)

print("labels train", y_train)
print("labels test", y_test)
# decoded_labels = label_encoder.inverse_transform(y_train)
# print("Rótulos Decodificados:", decoded_labels)

X_binary_train  = create_binary_array_docs(X_df_train, unique_words_set_train)
X_frequency_train = create_word_frequency(X_df_train, unique_words_set_train)
X_tfidf_train = calcule_tfidf(X_frequency_train)

X_train = [X_binary_train, X_frequency_train, X_tfidf_train ]

X_binary_test = create_binary_array_docs(X_df_test, unique_words_set_train)
X_frequency_test = create_word_frequency(X_df_test, unique_words_set_train)
X_tfidf_test = calcule_tfidf(X_frequency_test)

X_test = [X_binary_test , X_frequency_test , X_tfidf_test ]

labels train [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4
 4 4 4 4 4 4 4]
labels test [0 0 0 1 1 1 2 2 2 2 3 3 3 4 4]


In [12]:
from sklearn.metrics import accuracy_score, log_loss
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, LinearSVC, NuSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report


import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

genres = df['genre'].unique()

names = [
    "Nearest Neighbors",
    "Linear SVM",
    "RBF SVM",
    "Gaussian Process",
    "Decision Tree",
    "Random Forest",
    "Neural Net",
    "AdaBoost",
    "Naive Bayes",
]

classifiers = [
    KNeighborsClassifier(3),
    SVC(kernel="linear", C=0.025, random_state=42),
    SVC(gamma=2, C=1, random_state=42),
    GaussianProcessClassifier(1.0 * RBF(1.0), random_state=42),
    DecisionTreeClassifier(max_depth=5, random_state=42),
    RandomForestClassifier(
        max_depth=5, n_estimators=10, max_features=1, random_state=42
    ),
    MLPClassifier(alpha=1, max_iter=1000, random_state=42),
    AdaBoostClassifier(algorithm="SAMME", random_state=42),
    GaussianNB(),
]




for idx,(X_train_idx, X_test_idx) in enumerate(zip(X_train, X_test)):

  print(f'*************** Conjunto de teste {idx + 1} ****************************')
  for name, clf in zip(names, classifiers):

      clf.fit(X_train_idx, y_train)

      y_test_pred = clf.predict(X_test_idx)
      y_train_pred = clf.predict(X_train_idx)

      acc = accuracy_score(y_test, y_test_pred)
      print("-------------------- {} ----------------------".format(name))
      test_report = classification_report(y_test, y_test_pred, target_names=genres, zero_division=0)
      train_report = classification_report(y_train, y_train_pred, target_names=genres, zero_division=0)
      print('Train report')
      print(train_report)
      print('Test report')
      print(test_report)

      print("{}: Accuracy: {:.4%}".format(name, acc))
      conf_max = confusion_matrix(y_test, y_test_pred)
      print(f"Confusion Matrix:\n{conf_max}")


      # score = clf.score(X_test_idx, y_pred_test)
      # print("{}: Score: {:.4%}".format(name, score))


  print("="*30)

*************** Conjunto de teste 1 ****************************
-------------------- Nearest Neighbors ----------------------
Train report
               precision    recall  f1-score   support

     business       0.60      0.75      0.67         8
entertainment       0.36      0.62      0.45         8
     politics       0.67      1.00      0.80        12
        sport       1.00      0.25      0.40         8
         tech       0.00      0.00      0.00         8

     accuracy                           0.57        44
    macro avg       0.52      0.53      0.46        44
 weighted avg       0.54      0.57      0.49        44

Test report
               precision    recall  f1-score   support

     business       0.60      1.00      0.75         3
entertainment       0.50      0.33      0.40         3
     politics       0.50      1.00      0.67         4
        sport       0.00      0.00      0.00         3
         tech       0.00      0.00      0.00         2

     accuracy     

In [13]:
unique_words_set_train
print(len(unique_words_set_train))

2885


## Referências

In [14]:
from IPython.display import display, Math

# Exibindo a fórmula do TF-IDF
display(Math(r'\text{TF-IDF}(t, d, D) = \text{TF}(t, d) \times \text{IDF}(t, D)'))
display(Math(r'\text{TF}(t, d) = \frac{\text{Número de ocorrências de } t \text{ em } d}{\text{Número total de palavras em } d}'))
display(Math(r'\text{IDF}(t, D) = \log \frac{\text{Número total de documentos em } D}{1 + \text{Número de documentos contendo } t}'))


<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>